### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by pkofod** [cortner/ConstrainedOptim.jl#6]
@cortner I am all :+1: the name change, but where did the files go? :)

**Comment by cortner** [comment]
ouch - no idea how this happened - shows I shouldn't be doing those sort of updates on weekends. Give me 5 minutes.

**Comment by pkofod** [comment]
You probably `git rm src/AugmentedLagrangianMethod.jl` and forgot to `git add src/ConstrainedOptim.jl` :)

**Comment by cortner** [comment]
yep. - the advantage was that tests were passing :)

**Comment by cortner** [comment]
anyhow it should be ok now. sorry about this.

**Comment by pkofod** [comment]
no problem!
